services:
  redis:
    image: redis:7-alpine
    container_name: headcount_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: headcount_mediamtx
    ports:
      - "8889:8889" # WebRTC
      - "8554:8554" # RTSP
      - "8189:8189/udp" # WebRTC ICE
    volumes:
      - ./deepstream/mediamtx.yml:/mediamtx.yml
    restart: unless-stopped

  deepstream:
    image: nvcr.io/nvidia/deepstream:9.0-triton-multiarch
    container_name: headcount_deepstream
    ipc: host
    privileged: true
    depends_on:
      - redis
      - mediamtx
    environment:
      - REDIS_HOST=redis
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/workspace
      - ./recordings:/workspace/recordings
    command: bash /workspace/deepstream/start_ds.sh
    working_dir: /workspace/deepstream
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

    restart: unless-stopped

  amc-backend:
    image: nvcr.io/nvidia/auto-magic-calib:2.0.0
    container_name: headcount_amc_backend
    privileged: true
    environment:
      - HOST_IP=127.0.0.1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/home/auto-calibration-ms/server
    volumes:
      - ./recordings:/recordings
      - ./amc_calibration:/home/auto-calibration-ms/server/projects
      - ./models:/home/auto-calibration-ms/server/models
    working_dir: /home/auto-calibration-ms/server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: unless-stopped

  amc-ui:
    image: nvcr.io/nvidia/auto-magic-calib-ui:2.0.0
    container_name: headcount_amc_ui
    ports:
      - "5001:80"
    environment:
      - API_URL=http://headcount_amc_proxy:8000
      - VITE_API_URL=http://headcount_amc_proxy:8000
      - REACT_APP_API_URL=http://headcount_amc_proxy:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    depends_on:
      - amc-backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: headcount_backend
    depends_on:
      - redis
      - deepstream
    environment:
      - REDIS_HOST=redis
      - DS_API_BASE=deepstream:8010
      - FLASK_ENV=production
    ports:
      - "5002:5000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./zones.json:/app/zones.json
    restart: unless-stopped
